name: CI
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@8163dcea2f01a0a8fec84b284406ff7af1d2e1c0
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Unit tests

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 #v2.4.0
        with:
          version: ^6.32.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache npm artifacts
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-pnpm-cache
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}

      - name: Install npm dependencies
        run: pnpm install

      - name: Check for typeerrors
        run: pnpm build:lint

      - name: Run unit tests
        run: pnpm test:unit
