name: Push Metrics Fixture Generation
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  dummy-job:
    name: my dummy job
    runs-on: ubuntu-18.04
    steps:
      - name: Dummy step 1
        uses: actions/checkout@v3
      - name: Collect Metrics
        uses: ./.github/actions/push-metrics/
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: my dummy job

      - name: Dummy step 2
        id: dummy-step-2
        run: echo "test test test"

  dummy-job-dep:
    name: my dummy job
    needs: [dummy-job]
    runs-on: ubuntu-18.04
    steps:
      - name: Dummy step 1
        uses: actions/checkout@v3

      - name: Collect Metrics
        uses: ./.github/actions/push-metrics/
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: my dummy job

      - name: Dummy step 2
        id: dummy-step-2
        run: echo "test test test"

  generate-fixtures:
    name: generate-fixtures-name-${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        name: ["1", "2"]
    env:
      test-dir: ./.github/actions/push-metrics/test/
      fixture-path: fixtures/${{ github.event_name }}
      payload-name:
        ${{ github.run_id }}-${{ github.run_attempt }}-${{ github.event_name }}
    steps:
      - name: Dummy step 1
        uses: actions/checkout@v3

      - name: Collect Metrics
        uses: ./.github/actions/push-metrics/
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: generate-fixtures-name-${{ matrix.name }}
      - name: Remove old fixtures
        shell: bash
        run:
          rm -rf ${{ env.test-dir }}${{ env.fixture-path }}/{api,event,context}

      - name: Create required directories
        shell: bash
        run:
          mkdir -p ${{ env.test-dir }}${{ env.fixture-path
          }}/{api,event,context}

      - name: Dummy step 2
        id: dummy-step-2
        run: echo "test test test"

      - name: Gather API fixtures
        env:
          GH_TOKEN: ${{ github.token }}
          ATTEMPT_NUMBER: ${{ github.run_attempt }}
          RUN_ID: ${{ github.run_id }}
          EVENT_NAME: ${{ github.event_name }}
        run: ./scripts/generate-fixtures.sh
        working-directory: ${{ env.test-dir }}
        shell: bash

      - name: Dummy step 2
        id: dummy-step-22
        run: echo "test test test test"

      - name: Dump context
        uses: actions/github-script@v6
        env:
          dumpPath: ${{ env.test-dir }}${{ env.fixture-path }}/context/
        with:
          script: |
            const fs = require('fs')
            const path = require('path')
            fs.writeFileSync(path.join(process.env.dumpPath, 'context.json'), JSON.stringify(context))

      - name: Rename event JSON
        working-directory: ${{ env.test-dir }}
        run:
          mv ${{ github.event_path }} ./${{ env.fixture-path }}/event/${{
          env.payload-name }}.json

      - name: Upload fixtures
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.payload-name }}
          path: ${{ env.test-dir }}fixtures/
