name: Sync github push gha metrics source

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *" # Runs every hour

jobs:
  update-version:
    # TODO: Use GATI so workflows can run automatically
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v2
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Update Version
        continue-on-error: true

      - name: Checkout the repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Update version
        env:
          GH_TOKEN: ${{ secrets.GHA_ACTIONS_SOURCE_PULL_TOKEN }}
        run: ./sync-from-source/sync.sh

      - name: Open PR
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          title: Update push-gha-metrics-action
          branch: chore/update-push-gha-metrics-action
          commit-message: Update push-gha-metrics-action

  update-snapshot:
    # TODO: Use GATI so workflows can run automatically
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    name: Update snapshot version
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v2
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Update Version
        continue-on-error: true

      - name: Checkout the repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: snapshot

      - name: Pull changes
        env:
          GH_TOKEN: ${{ secrets.GHA_ACTIONS_SOURCE_PULL_TOKEN }}
        run: ./sync-from-source/sync.sh --snapshot

      - name: check for changes
        id: check_for_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_exist=true" >> $GITHUB_ENV
          else
            echo "changes_exist=false" >> $GITHUB_ENV
          fi

      - name: Commit and push files
        if: env.changes_exist == 'true'
        uses: planetscale/ghcommit-action@0e97298607962b704612dd4b7677600fdc363a21 # v0.1.17
        with:
          commit_message: "Sync with push-gha-metrics-action-source@main"
          repo: ${{ github.repository }}
          branch: snapshot
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
