name: test

on:
  workflow_dispatch:
    inputs:
      force-update-versions:
        type: boolean
        description: Force update-version job to run on non-main branch
        required: true
        default: false

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Test if
        if: ${{ github.event.inputs.force-update-versions }} || ${{ github.head_ref || github.ref_name }} == 'main'
        run: |
          echo "${{ github.event.inputs.force-update-versions }} || ${{ github.head_ref || github.ref_name }} == 'main'"